### ISSUE TITLE
Mentions Markdown Support in TextField

### ISSUE THREAD

**Issue by LaatonWalaBhoot** [wingio/syntakts#6]
Hi, I apologize for asking this as an issue. I understand this is more of a discussion topic.
But how can I use this for parsing and triggering mentions selection like in Discord while the input is being typed?

I assume this would be quite a common use case. I have been able to successfully display the mentions once I have the text but running into all sorts of issues in typed text.

Congratulations. This is a great port for CMP/KMP

**Comment by wingio** [comment]
you should be able to use TextFieldValue as it can take an AnnotatedString

**Comment by LaatonWalaBhoot** [comment]
Yeah that part is quite straightforward. What I am talking about is supporting replacement spans. Removing entire span on backspace and inserting in the middle of the text. I dont think there is any markdown library which does something similar to that. For reference: https://github.com/linkedin/Spyglass
